server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

spring:
  application:
    name: rent-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath:mapper/*Mapper.xml

api:
  enable: true
  secret: b1c2RoS7jJQkVMGY
  # 网关签名校验白名单
  white:
    #- /car/createNewReserve